"""Update DiagnosisResult model

Revision ID: 396ef91259e1
Revises: 7c273af41151
Create Date: 2024-09-24 06:32:26.486663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '396ef91259e1'
down_revision = '7c273af41151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parasite_density', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_wbcs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wbc_count', sa.Integer(), nullable=True))
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('parasite_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('average_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('severity_level',
               existing_type=postgresql.ENUM('low', 'medium', 'high', name='severity_levels'),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('positive', 'negative', 'inconclusive', name='result_status'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis_results', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('positive', 'negative', 'inconclusive', name='result_status'),
               nullable=False)
        batch_op.alter_column('severity_level',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('low', 'medium', 'high', name='severity_levels'),
               nullable=False)
        batch_op.alter_column('average_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('parasite_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('wbc_count')
        batch_op.drop_column('total_wbcs')
        batch_op.drop_column('parasite_density')

    # ### end Alembic commands ###
